import { db } from "./client";
import { keywords } from "./schema";

async function seed() {
  const data = [
    { kwId: "KW-000001", rawKeyword: "smart dhikr jewelry", normalizedKeyword: "smart dhikr jewelry", language: "EN", batchId: "BATCH-202604", sourceNum: "0" as const, sourceName: "第一方数据词", sourceDesc: "GA4 + GSC", wordType: "brand" as const, bp: "3" as const, sv: 4400, tp: 280, kd: 32, cpc: 0.68, growth: "rising" as const, cp: "high" as const, cs: "commercial" as const, sa: "enterable" as const, clusterCode: "CL-0001", headKeyword: "smart dhikr jewelry", clusterRole: "head" as const, layer: "L1" as const, handling: "independent" as const, cannibalization: "low" as const, status: "evaluated" as const },
    { kwId: "KW-000002", rawKeyword: "smart dhikr ring", normalizedKeyword: "smart dhikr ring", language: "EN", batchId: "BATCH-202604", sourceNum: "0" as const, sourceName: "第一方数据词", sourceDesc: "GA4 + GSC", wordType: "brand" as const, bp: "3" as const, sv: 3200, tp: 220, kd: 28, cpc: 0.55, growth: "rising" as const, cp: "high" as const, cs: "commercial" as const, sa: "enterable" as const, clusterCode: "CL-0001", headKeyword: "smart dhikr jewelry", clusterRole: "modifier" as const, layer: "L1" as const, handling: "independent" as const, cannibalization: "low" as const, status: "evaluated" as const },
    { kwId: "KW-000003", rawKeyword: "tasbih", normalizedKeyword: "tasbih", language: "EN", batchId: "BATCH-202604", sourceNum: "1" as const, sourceName: "内部词根", sourceDesc: "核心产品词", wordType: "category" as const, bp: "3" as const, sv: 18000, tp: 1200, kd: 45, cpc: 1.20, growth: "stable" as const, cp: "medium" as const, cs: "commercial" as const, sa: "cautious" as const, clusterCode: "CL-0002", headKeyword: "tasbih", clusterRole: "head" as const, layer: "L1" as const, handling: "independent" as const, cannibalization: "medium" as const, status: "pending" as const },
    { kwId: "KW-000004", rawKeyword: "itasbih", normalizedKeyword: "itasbih", language: "EN", batchId: "BATCH-202604", sourceNum: "1" as const, sourceName: "内部词根", sourceDesc: "品牌变体词", wordType: "brand" as const, bp: "3" as const, sv: 1280, tp: 90, kd: 15, cpc: 0.45, growth: "rising" as const, cp: "high" as const, cs: "commercial" as const, sa: "enterable" as const, clusterCode: "CL-0002", headKeyword: "tasbih", clusterRole: "variant" as const, layer: "L1" as const, handling: "independent" as const, cannibalization: "low" as const, status: "evaluated" as const },
    { kwId: "KW-000005", rawKeyword: "islamic jewelry", normalizedKeyword: "islamic jewelry", language: "EN", batchId: "BATCH-202604", sourceNum: "2" as const, sourceName: "一级竞品词", sourceDesc: "Semrush KW Gap", wordType: "category" as const, bp: "3" as const, sv: 9900, tp: 680, kd: 52, cpc: 1.80, growth: "stable" as const, cp: "medium" as const, cs: "commercial" as const, sa: "cautious" as const, clusterCode: "CL-0003", headKeyword: "islamic jewelry", clusterRole: "head" as const, layer: "L1" as const, handling: "independent" as const, cannibalization: "medium" as const, status: "pending" as const },
    { kwId: "KW-000006", rawKeyword: "gold name necklace", normalizedKeyword: "gold name necklace", language: "EN", batchId: "BATCH-202604", sourceNum: "2" as const, sourceName: "一级竞品词", sourceDesc: "Semrush KW Gap", wordType: "attribute" as const, bp: "2" as const, sv: 6600, tp: 450, kd: 38, cpc: 2.10, growth: "stable" as const, cp: "medium" as const, cs: "commercial" as const, sa: "enterable" as const, clusterCode: "CL-0004", headKeyword: "gold name necklace", clusterRole: "head" as const, layer: "L1" as const, handling: "independent" as const, cannibalization: "medium" as const, status: "evaluated" as const },
    { kwId: "KW-000101", rawKeyword: "kaaba direction", normalizedKeyword: "kaaba direction", language: "EN", batchId: "BATCH-202604", sourceNum: "4" as const, sourceName: "SERP特征词", sourceDesc: "PAA提取", wordType: "tool" as const, bp: "2" as const, sv: 2400, tp: 180, kd: 22, cpc: 0.30, growth: "stable" as const, cp: "high" as const, cs: "informational" as const, sa: "enterable" as const, clusterCode: "CL-0101", headKeyword: "tasbih", clusterRole: "modifier" as const, layer: "L2" as const, handling: "merge" as const, cannibalization: "low" as const, status: "evaluated" as const },
    { kwId: "KW-000102", rawKeyword: "salat app", normalizedKeyword: "salat app", language: "EN", batchId: "BATCH-202604", sourceNum: "4" as const, sourceName: "SERP特征词", sourceDesc: "Related Searches", wordType: "tool" as const, bp: "2" as const, sv: 1800, tp: 130, kd: 19, cpc: 0.25, growth: "rising" as const, cp: "high" as const, cs: "mixed" as const, sa: "enterable" as const, clusterCode: "CL-0102", headKeyword: "itasbih", clusterRole: "modifier" as const, layer: "L2" as const, handling: "merge" as const, cannibalization: "medium" as const, status: "pending" as const },
    { kwId: "KW-000103", rawKeyword: "night routine", normalizedKeyword: "night routine", language: "EN", batchId: "BATCH-202604", sourceNum: "6" as const, sourceName: "社交听取词", sourceDesc: "Reddit/YouTube", wordType: "scene" as const, bp: "1" as const, sv: 33000, tp: 800, kd: 68, cpc: 0.15, growth: "rising" as const, cp: "low" as const, cs: "informational" as const, sa: "blocked" as const, clusterCode: "CL-0103", headKeyword: "islamic jewelry", clusterRole: "modifier" as const, layer: "L2" as const, handling: "defer" as const, cannibalization: "high" as const, status: "pending" as const },
    { kwId: "KW-000104", rawKeyword: "islamic gifts", normalizedKeyword: "islamic gifts", language: "EN", batchId: "BATCH-202604", sourceNum: "2" as const, sourceName: "一级竞品词", sourceDesc: "Semrush KW Gap", wordType: "scene" as const, bp: "2" as const, sv: 4400, tp: 310, kd: 35, cpc: 1.50, growth: "stable" as const, cp: "medium" as const, cs: "commercial" as const, sa: "enterable" as const, clusterCode: "CL-0104", headKeyword: "islamic jewelry", clusterRole: "modifier" as const, layer: "L2" as const, handling: "merge" as const, cannibalization: "medium" as const, status: "evaluated" as const },
  ];

  await db.insert(keywords).values(data as any).onConflictDoNothing();
  console.log("Seed complete: 10 keywords inserted");
  process.exit(0);
}

seed().catch(console.error);
